package database;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

public class Insert_Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Update_Employee
     */
    public Insert_Supplier() {
        initComponents();
        mySettings();
        formLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSupplierProductName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtSupplierOrderStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierEmail = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSupplierMobile = new javax.swing.JTextField();
        txtSupplierCompany = new javax.swing.JComboBox<>();
        txtSupplierName = new javax.swing.JComboBox<>();
        txtSupplierProductID = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setTitle("ORDERING FORM");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("INSERT SUPPLIER");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Email Address");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Product Name");

        txtSupplierProductName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierProductName.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Supplier Name");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Product ID");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Order Stock");

        txtSupplierOrderStock.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierOrderStock.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Company Address");

        txtSupplierAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierAddress.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Mobile Phone");

        txtSupplierEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierEmail.setToolTipText("");

        btnSubmit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Supplier Company");

        txtSupplierMobile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierMobile.setToolTipText("");

        txtSupplierCompany.setEditable(true);
        txtSupplierCompany.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        txtSupplierCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCompanyActionPerformed(evt);
            }
        });

        txtSupplierName.setEditable(true);
        txtSupplierName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });

        txtSupplierProductID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSupplierProductID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        txtSupplierProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierProductIDActionPerformed(evt);
            }
        });
        
        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Order Date :");

        lblDate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDate.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDate))
                    .addComponent(txtSupplierOrderStock, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtSupplierProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txtSupplierMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupplierCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupplierProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDate))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierOrderStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                   

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	try{
    		int mp = Integer.parseInt(txtSupplierOrderStock.getText());
    		String mn = (String) txtSupplierProductID.getSelectedItem();
    		int ms = 0;
    		try{
    			Class.forName("com.mysql.jdbc.Driver").newInstance();
    		    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
    		    Statement stmt = con.createStatement();
    		    String quer = "SELECT * FROM item1 where product_id = '"+mn+"';";
    		    ResultSet rs = stmt.executeQuery(quer);
    		    while(rs.next()) 
    		    {ms = rs.getInt("stock_in_hand");}
    		    ms = ms + mp;
    		    String my = "" + ms;
    		    String query = "update item1 set Stock_in_hand = '"+ my +"'where product_id = '"+ mn +"';";
    		    Statement stm = con.createStatement();
    		    int rv = stm.executeUpdate(query);
    		    rs.close(); 
    		   
    		     stmt.close();
    		     stm.close();
    		     con.close();
    		}
    		catch(Exception b)
            {
                 JOptionPane.showMessageDialog(this,"Enter Data Correctly");
            }
    		try{
    			Class.forName("com.mysql.jdbc.Driver").newInstance();
    			Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
    			Statement stmt = con.createStatement();
    			String query = "Insert into item4(order_date, supplier_name, supplier_company, supplier_address, supplier_mobile, supplier_email, product_id, product_name, stock) values('"+lblDate.getText()+"', '"+txtSupplierName.getSelectedItem()+"', '"+txtSupplierCompany.getSelectedItem()+"', '"+txtSupplierAddress.getText()+"', '"+txtSupplierMobile.getText()+"', '"+txtSupplierEmail.getText()+"', '"+mn+"', '"+txtSupplierProductName.getText()+"', '"+mp+"');";
    			stmt.executeUpdate(query);
    			JOptionPane.showMessageDialog(this,"Record has been inserted");
    			stmt.close();
    			con.close();
    			txtSupplierName.setSelectedItem(null);
    			txtSupplierCompany.setSelectedItem(null);
    			txtSupplierAddress.setText(null);
    			txtSupplierMobile.setText(null);
    			txtSupplierEmail.setText(null);
    			txtSupplierProductID.setSelectedItem(null);
    			txtSupplierProductName.setText(null);
    			txtSupplierOrderStock.setText(null);
    		}
    		catch(Exception b)
    		{
    			JOptionPane.showMessageDialog(this,"Invalid Entry or data is too long in any field");
    		} 
    	}
    	catch(Exception mj )
    	{
    		JOptionPane.showMessageDialog(this, "Please Enter Data Correctly");
    	}
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	txtSupplierName.setSelectedItem(null);
    	txtSupplierCompany.setSelectedItem(null);
    	txtSupplierAddress.setText(null);
    	txtSupplierMobile.setText(null);
    	txtSupplierEmail.setText(null);
    	txtSupplierProductID.setSelectedItem(null);
    	txtSupplierProductName.setText(null);
    	txtSupplierOrderStock.setText(null);
    }                                        

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        dispose();
    }                                       

    private void txtSupplierCompanyActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	txtSupplierName.removeAllItems();
    	try{
        		Class.forName("com.mysql.jdbc.Driver").newInstance();
        		Connection co = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
        		Statement stm = co.createStatement();
        		String sql = "Select distinct supplier_name from item4 where supplier_company = '" + txtSupplierCompany.getSelectedItem() + "'";
        		ResultSet rs = stm.executeQuery(sql);
        		while(rs.next())
        		{
        			txtSupplierName.addItem(rs.getString("supplier_name"));
        		}
        	}
        catch(Exception e)
        {
        	JOptionPane.showMessageDialog(this,"Error in connectivity" );
        }  
   }
    
    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        try{
        	Class.forName("com.mysql.jdbc.Driver").newInstance();
        	Connection co = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
        	Statement stm = co.createStatement();
        	String sql = "Select * from item4 where supplier_company = '" + txtSupplierCompany.getSelectedItem() + "' and supplier_name = '" + txtSupplierName.getSelectedItem() + "'";
        	ResultSet rs = stm.executeQuery(sql);
        	while(rs.next())
        	{
        		String supplierAddress = rs.getString("supplier_address");
        		txtSupplierAddress.setText(supplierAddress);
        		String supplierMobile = rs.getString("supplier_mobile");
        		txtSupplierMobile.setText(supplierMobile);
        		String supplierEmail = rs.getString("supplier_email");
        		txtSupplierEmail.setText(supplierEmail);
        	}
        }
        catch(Exception e)
        {
        	JOptionPane.showMessageDialog(this,"Error in connectivity" );
        }
        txtSupplierProductID.removeAllItems();
        try{
        		Class.forName("com.mysql.jdbc.Driver").newInstance();
        	    Connection co = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
        	    Statement stm = co.createStatement();
        		String sql = "Select product_id from item1 where stock_in_hand <= 20";
        		ResultSet rs = stm.executeQuery(sql);
        		while(rs.next())
        		{
        			txtSupplierProductID.addItem(rs.getString("product_id"));
        		}
        }
        catch(Exception e)
        {
        	JOptionPane.showMessageDialog(this,"Error in connectivity" );
        }  
        }
        
    
    private void txtSupplierProductIDActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        	try{
        		Class.forName("com.mysql.jdbc.Driver").newInstance();
        	    Connection co = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
        	    Statement stm = co.createStatement();
        		String sql = "Select * from item1 where product_id = '" + txtSupplierProductID.getSelectedItem() + "'";
        		ResultSet rs = stm.executeQuery(sql);
        		while(rs.next())
        		{
        			String productName = rs.getString("product_name");
        			txtSupplierProductName.setText(productName);
        		}
        	}
        	catch(Exception e)
        	  {
        	      JOptionPane.showMessageDialog(this,"Error in connectivity" );
        	  }  
        }
    
    public void mySettings(){
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    public void formLoad(){
    	try{
    		Class.forName("com.mysql.jdbc.Driver").newInstance();
    	    Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
    	    Statement stmt = con.createStatement();
    		String sql = "Select CURRENT_DATE() AS Date";
    		ResultSet rs = stmt.executeQuery(sql);
    		while(rs.next())
    		{
    			String todayDate = rs.getString("Date");
    			lblDate.setText(todayDate);
    		}
    		rs.close();
    		stmt.close();
    		con.close();
    	}
    	catch(Exception e)
    	{
    		JOptionPane.showMessageDialog(this, "Error in connectivity");
    	}
    	try{
    		Class.forName("com.mysql.jdbc.Driver").newInstance();
    	    Connection co = (Connection)DriverManager.getConnection("jdbc:mysql://192.168.0.2/ken", "database", "");
    	    Statement stm = co.createStatement();
    		String sql = "Select distinct supplier_company from item4";
    		ResultSet rs = stm.executeQuery(sql);
    		while(rs.next())
    		{
    			txtSupplierCompany.addItem(rs.getString("supplier_company"));
    		}
    	}
    	catch(Exception e)
    	{
    		JOptionPane.showMessageDialog(this,"Error in connectivity" );
    	}
    	txtSupplierName.setSelectedItem(null);
		txtSupplierCompany.setSelectedItem(null);
		txtSupplierAddress.setText(null);
		txtSupplierMobile.setText(null);
		txtSupplierEmail.setText(null);
		txtSupplierProductID.setSelectedItem(null);
		txtSupplierProductName.setText(null);
		txtSupplierOrderStock.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Supplier().setVisible(true);
            }
        });
    }

 // Variables declaration - do not modify                     
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JComboBox<String> txtSupplierCompany;
    private javax.swing.JTextField txtSupplierEmail;
    private javax.swing.JTextField txtSupplierMobile;
    private javax.swing.JComboBox<String> txtSupplierName;
    private javax.swing.JTextField txtSupplierOrderStock;
    private javax.swing.JComboBox<String> txtSupplierProductID;
    private javax.swing.JTextField txtSupplierProductName;
    // End of variables declaration                   
}
